Rabbitmq helm
makeplane/helm-charts pull request #31
Opened 2024-09-03 13:40 UTC by akshat5302

2024-09-03 14:46 UTC, mguptahub reviewed
Please pull latest `develop` branch and then recheck the merge request

2024-09-03 14:46 UTC, mguptahub commented on charts/plane-ce/values.yaml
> +  image: rabbitmq:3-management
change the image to `rabbitmq:3.13.6-management-alpine`

2024-09-03 14:46 UTC, mguptahub commented on charts/plane-ce/templates/workloads/rabbitmq.stateful.yaml
> +  clusterIP: None
something missing. 
  ```
  {{- if not .Values.rabbitmq.assign_cluster_ip }}
  clusterIP: None
  {{- end }}
```

2024-09-03 14:46 UTC, mguptahub commented on charts/plane-ce/values.yaml
> +
add `assign_cluster_ip: false`

2024-09-03 14:47 UTC, mguptahub requested changes
Please re-pull the `develop` branch in your branch and check the PR file changes

2024-09-03 15:26 UTC, akshat5302 commented on charts/plane-ce/values.yaml
> +  image: rabbitmq:3-management
changed to `rabbitmq:3.13.6-management-alpine`

2024-09-03 15:27 UTC, akshat5302 commented on charts/plane-ce/templates/workloads/rabbitmq.stateful.yaml
> +  clusterIP: None
added if block

2024-09-03 15:27 UTC, akshat5302 commented on charts/plane-ce/values.yaml
> +
done

2024-09-04 11:33 UTC, mguptahub approved these changes

2024-09-04 11:33 UTC, mguptahub commented on charts/plane-ce/Chart.yaml
> +version: 1.0.22
this should be `1.0.23`

2024-09-04 11:33 UTC, merged